### ISSUE TITLE
How to set up titan for tests?

### ISSUE THREAD

**Issue by spinus** [davebshow/aiogremlin#1]
Hi, 

I've set up titan (with cassandra and ES). I can connect to titan and execute simple stuff like "3+5".

When I run `./setup.py test` I get:

```
test_resp_session (tests.tests.GremlinClientSessionTest) ... /usr/lib/python3.4/asyncio/tasks.py:508: DeprecationWarning: asyncio.async() function is deprecated, use ensure_future()
  DeprecationWarning)
ok
test_session (tests.tests.GremlinClientSessionTest) ... ERROR
test_session_manual_reset (tests.tests.GremlinClientSessionTest) ... ERROR
test_session_reset (tests.tests.GremlinClientSessionTest) ... ERROR
test_session_set (tests.tests.GremlinClientSessionTest) ... ERROR
test_connection (tests.tests.GremlinClientTest) ... ok
test_execute (tests.tests.GremlinClientTest) ... ok
test_execute_error (tests.tests.GremlinClientTest) ... ok
test_rebinding (tests.tests.GremlinClientTest) ... ERROR
test_resp_stream (tests.tests.GremlinClientTest) ... ok
test_sub_waitfor (tests.tests.GremlinClientTest) ... ok
test_rebinding (tests.tests.SubmitTest) ... ERROR
test_submit (tests.tests.SubmitTest) ... ok
```

The errors are like:

```
aiogremlin.exceptions.GremlinServerError: Code [597]: SCRIPT_EVALUATION. The script submitted for processing evaluated in the {@code ScriptEngine} with errors and could not be  processed.Check the script submitted for syntax errors or other problems and then resubmit..{}
```

I use titan 0.9.0-M2-hadoop1. 
Do I need to do any set up? Or create some objects before the test?

**Comment by davebshow** [comment]
Hi there,

Well there are a couple problems. I originally wrote these tests to run against Gremlin Server 3.0.0 using the in memory TinkerGraph implementation, not against Titan. As the GA Titan release gets closer it is time to change this. The sessions tests are failing, because they use the script:

```
graph = TinkerFactory.createModern()
```

However, Titan doesn't use `TinkerFactory`, so that throws an error. The other tests that fail are the tests that use rebindings. The problem here is that support for rebindings was included in the Gremlin Server 3.0.0 GA release. Titan 0.9.0-M2-hadoop1 uses the Gremlin Server 3.0.0.M9 still, therefore, this  feature is not yet available for Titan.

What I will do sometime today is make some simple changes so the tests don't depend on the Tinkergraph implementation, and are a bit more generic. For now though, I guess the rebindings tests will just fail against Titan. I'll let you know and close the issue when I push the new tests.

Thanks for bringing this to my attention.

Dave

**Comment by davebshow** [comment]
That should do it. Let me know if you are still having problems.

**Comment by spinus** [comment]
Hi @davebshow ,
that was extremly quick. Thank you. I'll test and let you know.
I did 0.9.0-m2 installation cause I thought that proper version of gremlin is there, but apparently 3.0.0M9 is not enough, thanks for explenations. BTW I'm new in that topic (titan/gremlin/etc) but if you need any help here I can do stuff.

**Comment by davebshow** [comment]
@spinus Well it is good to get going with Titan anyway. I believe the Titan 1.0 GA release will be coming out in August, and it will use the Gremlin Server 3.0.0 (or maybe 3.1.0 ? idk). I am always open to contributions, and you simply using the client and opening issues if you see problems is a huge help.   Thanks again!

Dave

**Comment by spinus** [comment]
@davebshow cheers.
